### ISSUE TITLE
Traditional Chinese interface is not completely traditional Chinese ...

### ISSUE THREAD

**Issue by ioc2e3** [Floorp-Projects/Floorp-Portable#16]
Traditional Chinese interface is not completely traditional Chinese ...

Mixed English, Simplified Chinese ...

Even from this ( https://addons.mozilla.org/zh-TW/firefox/addon/traditional-chinese-zh-tw-l/ ) downloading traditional Chinese language files, the same ...

...............................

in addition ...

Why doesn't Portable Version automatic update work?

**Comment by typeling1578** [comment]
Please use esr versions:
https://ftp.mozilla.org/pub/firefox/releases/115.7.0esr/win64/xpi/
https://ftp.mozilla.org/pub/firefox/releases/115.7.0esr/linux-x86_64/xpi/


Also, see: https://github.com/Floorp-Projects/Floorp/discussions/624
