### ISSUE TITLE
Windows Portable Version is always out of date compared to the other releases

### ISSUE THREAD

**Issue by astatine** [Floorp-Projects/Floorp-Portable#21]
The current 64-bit installers release version is v11.11.1, whereas the portable release download link is stuck at v11.10.5.
![Floorp_portable_out_of_date](https://github.com/Floorp-Projects/Floorp-Portable/assets/1077402/5465c77b-e759-45b6-9867-be7fcb973efe)

Even the portable releases page shows that the latest release is v11.10.5.
![Floorp_releases_page](https://github.com/Floorp-Projects/Floorp-Portable/assets/1077402/7721c3ee-d83d-43f3-9dc6-04db07f06ba7)

**Comment by creeper-0910** [comment]
We apologize for any inconvenience caused.
We are currently updating the portable version.

**Comment by creeper-0910** [comment]
Fixed

**Comment by minus21grams** [comment]
An ETA would be helpful. Version 11.16.0 was released a week ago and 11.17.1 earlier today. 😐

**Comment by creeper-0910** [comment]
Sorry, we are currently preparing.

**Comment by creeper-0910** [comment]
Fixed
