### ISSUE TITLE
Self updater doesn't work

### ISSUE THREAD

**Issue by apfelchips** [Floorp-Projects/Floorp-Portable#22]
Hi,

I've recently started using the Floorp-Portable Release on Windows 10. 
Sadly the internal update mechanism seems to be broken here.

![image](https://github.com/Floorp-Projects/Floorp-Portable/assets/6919384/e5c91a9e-18b4-46c2-a522-a3507cc8f8be)
these are the notifications I receive, but the version doesn't change upon restart. v11.11.2 --> v11.12.2

I'd really like to use the portable version, but downloading the zip release and overwriting the installation is really cumbersome and not viable for a security critical program like a browser.

Are there plans to implement / fix the self update functionality of this distribution?

Thanks for developing Floorp and keeping web engine diversity alive.

**Comment by creeper-0910** [comment]
Thank you for your inquiry.
We apologize for the inconvenience, but could you please try the following?
・Make sure that the update_tmp folder is created in the same directory as floorp.exe, and close Floorp.
・Wait for 10 seconds and then start Floorp.

**Comment by apfelchips** [comment]
Hi,
thanks for the response.
I've updated to v11.12.2 manually so I couldn't reproduce the problem.
But now I have the same issue with v11.13.2. The folder update_tmp gets created and the update.zip is downloaded and extracted.

Closing and reopening floorp just deletes the updated_tmp folder and restarts the notifications / download without replacing the old executable with the new one.

![image](https://github.com/Floorp-Projects/Floorp-Portable/assets/6919384/7fb7dbd8-418f-4a16-85e2-a3d88c9d5dc3)

**Comment by creeper-0910** [comment]
This is due to the fact that it was reopened before the Floorp termination process was completed.

**Comment by apfelchips** [comment]
ok I've finally got it to work after replacing, not just overwriting / merging the core directory, maybe there were some old dlls / files in there that didn't get deleted and caused problems with the version updater, or maybe I was just too impatient.

Thanks again for providing this great Edition.

**Comment by creeper-0910** [comment]
I am glad it was resolved!
We hope you continue to enjoy Floorp!

**Comment by uugaabuugaa** [comment]
I'm having the same problem as this one. `update_tmp` is created and the notification tells me it will update on next launch. But on next launch it just starts downloading the update again and keeps going on a loop! I've waited about a minute after closing to see if that makes any difference but no. It just starts downloading the update again? I have the `floorp-portable-default.bat` within the main directory but I don't think that should make a difference.
