### ISSUE TITLE
Portable version is outdated compared to normal release

### ISSUE THREAD

**Issue by ashtrath** [Floorp-Projects/Floorp-Portable#24]
The portable version is always outdated compared to the normal release.
Until this day Floorp-Portable is missing 2 minor updates from the normal release.
This is causing issue to (probable windows only) user who use [Scoop](https://scoop.sh) to install their software since they rely on using the portable version of floorp.

Current portable release is at v11.13.1
![image](https://github.com/Floorp-Projects/Floorp-Portable/assets/69681505/461528c2-14c4-4e6f-896c-65d5d548c04e)

While the normal release already on v11.13.3
![image](https://github.com/Floorp-Projects/Floorp-Portable/assets/69681505/02c3c62f-2e73-4240-af68-ab4ccb40fa7b)

**Comment by creeper-0910** [comment]
Fixed

**Comment by minus21grams** [comment]
Bump.

**Comment by minus21grams** [comment]
Anyone? 🤔

**Comment by minus21grams** [comment]
Just a reminder: v1.26.0 was released earlier today - portable remains outdated...
