### ISSUE TITLE
"Failed to start floop"

### ISSUE THREAD

**Issue by ghost** [Floorp-Projects/Floorp-Portable#25]
Hello,
I am on windows and I tried to follow the instructions :
- I installed Go
- I placed all the sources files into a directory named `core`
- I runned `.\build.bat` from cmd
- I runned `patcher.exe` from cmd

And if I launch `floorp.exe` I get "Failed to start floop"

Thanks for any help
![Capture](https://github.com/Floorp-Projects/Floorp-Portable/assets/43271521/8cc010d7-a039-40ae-9ad4-491c9a251ac4)

**Comment by Ryosuke-Asano** [comment]
We do not support relating to build support on GitHub
