### ISSUE TITLE
Cannot set Workspace Container Tab

### ISSUE THREAD

**Issue by waruigi** [Floorp-Projects/Floorp-Portable#26]
When managing a Workspace, selecting a Container Tab doesn't work. It's stays as "No Container".
Last version where this worked was 11.13.3

**Comment by typeling1578** [comment]
Which platform do you use, Windows or Linux?

**Comment by typeling1578** [comment]
This issue has been inactive for a long period of time and has been closed.
If the problem continues to occur, please reopen it.
