### ISSUE TITLE
Requirements are not written.

### ISSUE THREAD

**Issue by universish** [Floorp-Projects/Floorp-Portable#39]
There is no information in the README about installing the golang package. 
could not build without installing golang package. please write requirements and dependencies in readme file. I'm not a programmer, I don't know how to do this.

**Comment by creeper-0910** [comment]
The build procedure for this project is structured for users with minimal knowledge.
It is possible to build the project without writing the golang package dependencies in the README.
This issue is not acceptable as it falls under the category of build inquiries.
