### ISSUE TITLE
Problem that @typeling1578 closed the unresolved problem. 

### ISSUE THREAD

**Issue by universish** [Floorp-Projects/Floorp-Portable#40]
Problem that @typeling1578 closed the unresolved problem. Review your maintainer.

**Comment by universish** [comment]
https://github.com/Floorp-Projects/Floorp-Portable/issues/38
https://github.com/Floorp-Projects/Floorp-Portable/issues/39

**Comment by creeper-0910** [comment]
Unsupported issues.
